from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from io import BytesIO

class ReportGenerator:
    """Generates PDF reports for resume analysis"""
    
    @staticmethod
    def generate_pdf(results: dict) -> bytes:
        """
        Generate PDF report from analysis results
        
        Args:
            results: Analysis results dictionary
            
        Returns:
            PDF bytes
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'Title',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=1  # Center
        )
        
        heading_style = ParagraphStyle(
            'Heading',
            parent=styles['Heading2'],
            fontSize=16,
            spaceBefore=20,
            spaceAfter=10,
            textColor=colors.HexColor('#1f77b4')
        )
        
        elements = []
        
        # Header
        elements.append(Paragraph("ATS Forge - Resume Analysis Report", title_style))
        elements.append(Spacer(1, 20))
        
        # Summary Score
        score = results['score']
        elements.append(Paragraph("Executive Summary", heading_style))
        
        summary_data = [
            ['Metric', 'Score', 'Status'],
            ['Overall Score', f"{score['total_score']}/100", score['grade']],
            ['Keyword Match', f"{score['keyword_score']}/100", f"{results['keyword_analysis']['match_results']['match_percentage']}% Match"],
            ['Formatting', f"{score['formatting_score']}/100", "Pass" if score['formatting_score'] >= 80 else "Check"],
            ['ATS Compliance', f"{score['ats_score']}/100", "Pass" if score['ats_score'] >= 80 else "Check"]
        ]
        
        t = Table(summary_data, colWidths=[150, 100, 150])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f0f2f6')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        elements.append(t)
        
        # Key Recommendations
        elements.append(Paragraph("Priority Recommendations", heading_style))
        recommendations = results.get('recommendations', [])
        
        if recommendations:
            for rec in recommendations[:5]:  # Top 5
                # Handle string recommendations (legacy) or dict (new)
                if isinstance(rec, dict):
                    text = f"• <b>[{rec['priority'].upper()}]</b> {rec['message']}"
                else:
                    text = f"• {rec}"
                elements.append(Paragraph(text, styles['Normal']))
                elements.append(Spacer(1, 5))
        else:
            elements.append(Paragraph("No major recommendations found. Great job!", styles['Normal']))
            
        # Found Skills (Top 20)
        elements.append(Paragraph("Matched Skills", heading_style))
        found = results['keyword_analysis']['match_results']['found_keywords'].get('all', [])
        if found:
            skills_text = ", ".join(found[:30])
            if len(found) > 30:
                skills_text += f", and {len(found) - 30} more..."
            elements.append(Paragraph(skills_text, styles['Normal']))
        else:
            elements.append(Paragraph("No skills found.", styles['Normal']))
            
        # Missing Skills
        elements.append(Paragraph("Missing Skills (High Priority)", heading_style))
        missing_tech = results['keyword_analysis']['match_results']['missing_keywords'].get('tech_skills', [])
        if missing_tech:
            elements.append(Paragraph(", ".join(missing_tech[:15]), styles['Normal']))
        else:
            elements.append(Paragraph("No critical technical skills missing.", styles['Normal']))
            
        # Disclaimer
        elements.append(Spacer(1, 40))
        elements.append(Paragraph("Generated by ATS Forge", styles['Italic']))
        
        # Build PDF
        doc.build(elements)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        return pdf_bytes
